export const POSTS_TYPES = {
  GET_POSTS: '@POSTS/GET_POSTS',
  GET_POSTS_SUCCESS: '@POSTS/GET_POSTS_SUCCESS',
  GET_POSTS_FAILURE: '@POSTS/GET_POSTS_FAILURE',
  CREATE_POST: '@POSTS/CREATE_POST',
  CREATE_POST_SUCCESS: '@POSTS/CREATE_POST_SUCCESS',
  CREATE_POST_FAILURE: '@POSTS/CREATE_POST_FAILURE',
  UPDATE_POST: '@POSTS/UPDATE_POST',
  UPDATE_POST_SUCCESS: '@POSTS/UPDATE_POST_SUCCESS',
  UPDATE_POST_FAILURE: '@POSTS/UPDATE_POST_FAILURE',
  DELETE_POST: '@POSTS/DELETE_POST',
  DELETE_POST_SUCCESS: '@POSTS/DELETE_POST_SUCCESS',
  DELETE_POST_FAILURE: '@POSTS/DELETE_POST_FAILURE'
}
